import React, { useState, useMemo } from 'react';
import {
  View, Text, StyleSheet, ScrollView, TouchableOpacity,
  TextInput, Alert, ActivityIndicator,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { useColors } from '../../constants/colors';
import { uploadDocument } from '../../api/features';

type DocType = 'rate_confirmation' | 'proof_of_delivery' | 'invoice';

const DOC_TYPES: Array<{ type: DocType; label: string; desc: string; icon: string; color: string }> = [
  { type: 'rate_confirmation', label: 'Rate Confirmation', desc: 'Load agreement between carrier and broker', icon: 'document-text-outline', color: '#3498DB' },
  { type: 'proof_of_delivery', label: 'Proof of Delivery', desc: 'Delivery receipt for completed loads', icon: 'checkmark-circle-outline', color: '#2ECC71' },
  { type: 'invoice', label: 'Freight Invoice', desc: 'Invoice for payment from broker/shipper', icon: 'receipt-outline', color: '#9B59B6' },
];

const today = () => new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
const todayStr = () => new Date().toISOString().split('T')[0];

function buildRateConfirmationHTML(f: Record<string, string>): string {
  return `<!DOCTYPE html><html><head><meta charset="utf-8">
<style>
body{font-family:Arial,sans-serif;margin:40px;color:#1a1a1a;font-size:13px;}
h1{color:#1a1a2e;font-size:22px;margin-bottom:4px;}
.subtitle{color:#666;font-size:12px;margin-bottom:24px;}
.header{display:flex;justify-content:space-between;align-items:flex-start;border-bottom:3px solid #F1C40F;padding-bottom:16px;margin-bottom:24px;}
.company{font-size:20px;font-weight:bold;color:#F1C40F;}
table{width:100%;border-collapse:collapse;margin-bottom:20px;}
th{background:#1a1a2e;color:#F1C40F;padding:8px 12px;text-align:left;font-size:12px;}
td{padding:8px 12px;border-bottom:1px solid #eee;}
.section-title{font-weight:bold;color:#1a1a2e;font-size:14px;margin:20px 0 8px;}
.rate-box{background:#F1C40F;color:#1a1a2e;padding:16px;border-radius:8px;text-align:center;margin:20px 0;}
.rate-value{font-size:32px;font-weight:900;}
.sig-block{margin-top:40px;display:flex;gap:40px;}
.sig-line{flex:1;border-top:1px solid #333;padding-top:8px;font-size:11px;color:#666;}
.footer{margin-top:30px;text-align:center;font-size:10px;color:#999;border-top:1px solid #eee;padding-top:12px;}
</style></head><body>
<div class="header">
<div><div class="company">CST Driver</div><div class="subtitle">Commercial Support Technologies</div></div>
<div><h1>Rate Confirmation</h1><div class="subtitle">Date: ${today()}</div></div>
</div>

<div class="section-title">Load Information</div>
<table><tr><th>Field</th><th>Details</th></tr>
<tr><td>Load Number</td><td>${f.loadNumber || 'N/A'}</td></tr>
<tr><td>Pickup Date</td><td>${f.pickupDate || 'N/A'}</td></tr>
<tr><td>Delivery Date</td><td>${f.deliveryDate || 'N/A'}</td></tr>
<tr><td>Commodity</td><td>${f.commodity || 'N/A'}</td></tr>
<tr><td>Weight</td><td>${f.weight ? f.weight + ' lbs' : 'N/A'}</td></tr>
<tr><td>Miles</td><td>${f.miles ? f.miles + ' miles' : 'N/A'}</td></tr>
</table>

<div class="section-title">Shipper (Pickup)</div>
<table><tr><th>Field</th><th>Details</th></tr>
<tr><td>Name</td><td>${f.shipperName || 'N/A'}</td></tr>
<tr><td>Address</td><td>${f.shipperAddress || 'N/A'}</td></tr>
<tr><td>City / State</td><td>${f.shipperCity || 'N/A'}, ${f.shipperState || 'N/A'}</td></tr>
</table>

<div class="section-title">Consignee (Delivery)</div>
<table><tr><th>Field</th><th>Details</th></tr>
<tr><td>Name</td><td>${f.consigneeName || 'N/A'}</td></tr>
<tr><td>Address</td><td>${f.consigneeAddress || 'N/A'}</td></tr>
<tr><td>City / State</td><td>${f.consigneeCity || 'N/A'}, ${f.consigneeState || 'N/A'}</td></tr>
</table>

<div class="section-title">Carrier Information</div>
<table><tr><th>Field</th><th>Details</th></tr>
<tr><td>Carrier Name</td><td>${f.carrierName || 'N/A'}</td></tr>
<tr><td>MC Number</td><td>${f.mcNumber || 'N/A'}</td></tr>
<tr><td>DOT Number</td><td>${f.dotNumber || 'N/A'}</td></tr>
<tr><td>Driver</td><td>${f.driverName || 'N/A'}</td></tr>
</table>

<div class="rate-box"><div>Agreed Rate</div><div class="rate-value">$${parseFloat(f.rate || '0').toLocaleString('en-US', { minimumFractionDigits: 2 })}</div>${f.miles && f.rate ? `<div>$${(parseFloat(f.rate) / parseFloat(f.miles)).toFixed(2)}/mile</div>` : ''}</div>

${f.notes ? `<div class="section-title">Notes</div><p>${f.notes}</p>` : ''}

<div class="sig-block">
<div class="sig-line">Carrier Signature &amp; Date</div>
<div class="sig-line">Broker Signature &amp; Date</div>
</div>
<div class="footer">Generated by CST Driver App · ${today()}</div>
</body></html>`;
}

function buildPODHTML(f: Record<string, string>): string {
  return `<!DOCTYPE html><html><head><meta charset="utf-8">
<style>
body{font-family:Arial,sans-serif;margin:40px;color:#1a1a1a;font-size:13px;}
h1{color:#1a1a2e;font-size:22px;}
.company{font-size:20px;font-weight:bold;color:#2ECC71;}
.header{display:flex;justify-content:space-between;border-bottom:3px solid #2ECC71;padding-bottom:16px;margin-bottom:24px;}
table{width:100%;border-collapse:collapse;margin-bottom:20px;}
th{background:#1a1a2e;color:#2ECC71;padding:8px 12px;text-align:left;}
td{padding:8px 12px;border-bottom:1px solid #eee;}
.delivered-box{background:#2ECC71;color:#fff;padding:16px;border-radius:8px;text-align:center;margin:20px 0;font-size:20px;font-weight:900;}
.sig-block{margin-top:40px;display:flex;gap:40px;}
.sig-line{flex:1;border-top:1px solid #333;padding-top:8px;font-size:11px;color:#666;}
.footer{margin-top:30px;text-align:center;font-size:10px;color:#999;border-top:1px solid #eee;padding-top:12px;}
</style></head><body>
<div class="header">
<div><div class="company">CST Driver</div></div>
<div><h1>Proof of Delivery</h1><div>Date: ${today()}</div></div>
</div>

<div class="delivered-box">✓ DELIVERED</div>

<table><tr><th>Field</th><th>Details</th></tr>
<tr><td>Load Number</td><td>${f.loadNumber || 'N/A'}</td></tr>
<tr><td>Delivery Date</td><td>${f.deliveryDate || todayStr()}</td></tr>
<tr><td>Delivery Time</td><td>${f.deliveryTime || 'N/A'}</td></tr>
<tr><td>Commodity</td><td>${f.commodity || 'N/A'}</td></tr>
<tr><td>Weight</td><td>${f.weight ? f.weight + ' lbs' : 'N/A'}</td></tr>
<tr><td>Pieces / Pallets</td><td>${f.pieces || 'N/A'}</td></tr>
<tr><td>Condition</td><td>${f.condition || 'Good — No Exceptions'}</td></tr>
</table>

<table><tr><th>Shipper</th><th>Consignee</th></tr>
<tr><td>${f.shipperName || 'N/A'}<br>${f.shipperCity || ''}, ${f.shipperState || ''}</td>
<td>${f.consigneeName || 'N/A'}<br>${f.consigneeCity || ''}, ${f.consigneeState || ''}</td></tr>
</table>

<div style="margin-top:16px"><strong>Received By:</strong> ${f.receivedBy || '_________________________'}</div>
${f.notes ? `<div style="margin-top:12px"><strong>Notes:</strong> ${f.notes}</div>` : ''}

<div class="sig-block">
<div class="sig-line">Driver Signature &amp; Date</div>
<div class="sig-line">Receiver Signature &amp; Date</div>
</div>
<div class="footer">Generated by CST Driver App · ${today()}</div>
</body></html>`;
}

function buildInvoiceHTML(f: Record<string, string>): string {
  const rate = parseFloat(f.rate || '0');
  const detention = parseFloat(f.detention || '0');
  const fuel = parseFloat(f.fuelSurcharge || '0');
  const total = rate + detention + fuel;
  return `<!DOCTYPE html><html><head><meta charset="utf-8">
<style>
body{font-family:Arial,sans-serif;margin:40px;color:#1a1a1a;font-size:13px;}
h1{color:#1a1a2e;font-size:22px;}
.company{font-size:20px;font-weight:bold;color:#9B59B6;}
.header{display:flex;justify-content:space-between;border-bottom:3px solid #9B59B6;padding-bottom:16px;margin-bottom:24px;}
table{width:100%;border-collapse:collapse;margin-bottom:20px;}
th{background:#1a1a2e;color:#9B59B6;padding:8px 12px;text-align:left;}
td{padding:8px 12px;border-bottom:1px solid #eee;}
.total-row{background:#f9f9f9;font-weight:bold;font-size:15px;}
.total-amount{color:#9B59B6;font-size:20px;font-weight:900;}
.bill-to{background:#f5f5f5;padding:14px;border-radius:8px;margin-bottom:20px;}
.footer{margin-top:30px;text-align:center;font-size:10px;color:#999;border-top:1px solid #eee;padding-top:12px;}
.due{background:#9B59B6;color:#fff;padding:10px;border-radius:6px;text-align:center;margin:16px 0;font-weight:700;}
</style></head><body>
<div class="header">
<div><div class="company">CST Driver</div><div>${f.carrierName || 'Carrier'}</div><div>MC# ${f.mcNumber || 'N/A'} · DOT# ${f.dotNumber || 'N/A'}</div></div>
<div><h1>FREIGHT INVOICE</h1><div>Invoice #: ${f.invoiceNumber || 'INV-' + Date.now().toString().slice(-6)}</div><div>Date: ${today()}</div></div>
</div>

<div class="bill-to"><strong>Bill To:</strong><br>${f.brokerName || 'Broker'}<br>${f.brokerAddress || ''}<br>${f.brokerEmail || ''}</div>

<table><tr><th>Description</th><th>Amount</th></tr>
<tr><td>Freight — Load #${f.loadNumber || 'N/A'}<br><small>${f.shipperCity || ''}, ${f.shipperState || ''} → ${f.consigneeCity || ''}, ${f.consigneeState || ''}</small><br><small>${f.miles ? f.miles + ' miles' : ''} · ${f.commodity || ''}</small></td><td>$${rate.toLocaleString('en-US', { minimumFractionDigits: 2 })}</td></tr>
${detention > 0 ? `<tr><td>Detention (${f.detentionHours || ''} hrs)</td><td>$${detention.toFixed(2)}</td></tr>` : ''}
${fuel > 0 ? `<tr><td>Fuel Surcharge</td><td>$${fuel.toFixed(2)}</td></tr>` : ''}
<tr class="total-row"><td>TOTAL DUE</td><td class="total-amount">$${total.toLocaleString('en-US', { minimumFractionDigits: 2 })}</td></tr>
</table>

<div class="due">PAYMENT DUE: ${f.dueDate || 'NET 30'}</div>

<div><strong>Remit To:</strong><br>${f.carrierName || ''}<br>${f.bankInfo || 'Please contact carrier for payment details'}</div>
${f.notes ? `<div style="margin-top:16px"><strong>Notes:</strong> ${f.notes}</div>` : ''}
<div class="footer">Generated by CST Driver App · ${today()}</div>
</body></html>`;
}

const FIELDS: Record<DocType, Array<{ label: string; key: string; ph: string; kbd?: 'decimal-pad' | 'phone-pad' }>> = {
  rate_confirmation: [
    { label: 'Load Number', key: 'loadNumber', ph: 'LD-0001' },
    { label: 'Carrier Name', key: 'carrierName', ph: 'Your Company Name' },
    { label: 'MC Number', key: 'mcNumber', ph: 'MC123456' },
    { label: 'DOT Number', key: 'dotNumber', ph: 'DOT1234567' },
    { label: 'Driver Name', key: 'driverName', ph: 'John Smith' },
    { label: 'Pickup Date', key: 'pickupDate', ph: 'YYYY-MM-DD' },
    { label: 'Delivery Date', key: 'deliveryDate', ph: 'YYYY-MM-DD' },
    { label: 'Shipper Name', key: 'shipperName', ph: 'ABC Manufacturing' },
    { label: 'Shipper Address', key: 'shipperAddress', ph: '123 Industrial Blvd' },
    { label: 'Shipper City', key: 'shipperCity', ph: 'Houston' },
    { label: 'Shipper State', key: 'shipperState', ph: 'TX' },
    { label: 'Consignee Name', key: 'consigneeName', ph: 'XYZ Distribution' },
    { label: 'Consignee Address', key: 'consigneeAddress', ph: '456 Warehouse Ave' },
    { label: 'Consignee City', key: 'consigneeCity', ph: 'Dallas' },
    { label: 'Consignee State', key: 'consigneeState', ph: 'TX' },
    { label: 'Commodity', key: 'commodity', ph: 'Dry goods / Electronics...' },
    { label: 'Weight (lbs)', key: 'weight', ph: '45000', kbd: 'decimal-pad' },
    { label: 'Miles', key: 'miles', ph: '500', kbd: 'decimal-pad' },
    { label: 'Rate ($)', key: 'rate', ph: '2500.00', kbd: 'decimal-pad' },
    { label: 'Notes', key: 'notes', ph: 'Special instructions...' },
  ],
  proof_of_delivery: [
    { label: 'Load Number', key: 'loadNumber', ph: 'LD-0001' },
    { label: 'Delivery Date', key: 'deliveryDate', ph: 'YYYY-MM-DD' },
    { label: 'Delivery Time', key: 'deliveryTime', ph: '2:30 PM' },
    { label: 'Shipper Name', key: 'shipperName', ph: 'ABC Manufacturing' },
    { label: 'Shipper City', key: 'shipperCity', ph: 'Houston' },
    { label: 'Shipper State', key: 'shipperState', ph: 'TX' },
    { label: 'Consignee Name', key: 'consigneeName', ph: 'XYZ Distribution' },
    { label: 'Consignee City', key: 'consigneeCity', ph: 'Dallas' },
    { label: 'Consignee State', key: 'consigneeState', ph: 'TX' },
    { label: 'Commodity', key: 'commodity', ph: 'Dry goods...' },
    { label: 'Weight (lbs)', key: 'weight', ph: '45000', kbd: 'decimal-pad' },
    { label: 'Pieces / Pallets', key: 'pieces', ph: '24 pallets' },
    { label: 'Condition', key: 'condition', ph: 'Good — No Exceptions' },
    { label: 'Received By', key: 'receivedBy', ph: 'Jane Doe' },
    { label: 'Notes', key: 'notes', ph: 'Any exceptions...' },
  ],
  invoice: [
    { label: 'Invoice Number', key: 'invoiceNumber', ph: 'INV-001' },
    { label: 'Load Number', key: 'loadNumber', ph: 'LD-0001' },
    { label: 'Carrier Name', key: 'carrierName', ph: 'Your Company Name' },
    { label: 'MC Number', key: 'mcNumber', ph: 'MC123456' },
    { label: 'DOT Number', key: 'dotNumber', ph: 'DOT1234567' },
    { label: 'Broker Name', key: 'brokerName', ph: 'XPO Logistics' },
    { label: 'Broker Email', key: 'brokerEmail', ph: 'ap@broker.com' },
    { label: 'Broker Address', key: 'brokerAddress', ph: '123 Broker St, City, ST' },
    { label: 'Shipper City', key: 'shipperCity', ph: 'Houston' },
    { label: 'Shipper State', key: 'shipperState', ph: 'TX' },
    { label: 'Consignee City', key: 'consigneeCity', ph: 'Dallas' },
    { label: 'Consignee State', key: 'consigneeState', ph: 'TX' },
    { label: 'Commodity', key: 'commodity', ph: 'Dry goods...' },
    { label: 'Miles', key: 'miles', ph: '500', kbd: 'decimal-pad' },
    { label: 'Freight Rate ($)', key: 'rate', ph: '2500.00', kbd: 'decimal-pad' },
    { label: 'Detention ($)', key: 'detention', ph: '0.00', kbd: 'decimal-pad' },
    { label: 'Detention Hours', key: 'detentionHours', ph: '0', kbd: 'decimal-pad' },
    { label: 'Fuel Surcharge ($)', key: 'fuelSurcharge', ph: '0.00', kbd: 'decimal-pad' },
    { label: 'Payment Terms', key: 'dueDate', ph: 'NET 30' },
    { label: 'Bank / Remit Info', key: 'bankInfo', ph: 'Zelle: email@example.com' },
    { label: 'Notes', key: 'notes', ph: 'Any notes...' },
  ],
};

export default function DocGeneratorScreen() {
  const Colors = useColors();
  const s = useMemo(() => StyleSheet.create({
    container: { flex: 1, backgroundColor: Colors.background },
    picker: { padding: 24, gap: 16 },
    heading: { color: Colors.text, fontSize: 22, fontWeight: '800', marginBottom: 4 },
    subheading: { color: Colors.textMuted, fontSize: 13, marginBottom: 16 },
    typeCard: { backgroundColor: Colors.surface, borderRadius: 16, borderWidth: 2, padding: 18, flexDirection: 'row', alignItems: 'center', gap: 16 },
    typeIcon: { width: 56, height: 56, borderRadius: 28, justifyContent: 'center', alignItems: 'center' },
    typeLabel: { color: Colors.text, fontSize: 16, fontWeight: '800', marginBottom: 4 },
    typeDesc: { color: Colors.textMuted, fontSize: 12 },
    formHeader: { flexDirection: 'row', alignItems: 'center', gap: 12, padding: 16, borderBottomWidth: 1, borderColor: Colors.border },
    backBtn: { width: 36, height: 36, borderRadius: 18, backgroundColor: Colors.primary, justifyContent: 'center', alignItems: 'center' },
    formTitle: { color: Colors.text, fontSize: 16, fontWeight: '800' },
    formSubtitle: { color: Colors.textMuted, fontSize: 12 },
    formBody: { padding: 20, gap: 4 },
    fieldLabel: { color: Colors.textMuted, fontSize: 13, marginTop: 10 },
    fieldInput: { backgroundColor: Colors.surface, borderRadius: 10, borderWidth: 1, borderColor: Colors.border, padding: 12, color: Colors.text, fontSize: 14, marginTop: 4 },
    generateBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 10, padding: 16, borderRadius: 14, marginTop: 24 },
    generateText: { color: '#fff', fontSize: 16, fontWeight: '800' },
  }), [Colors]);
  const [selected, setSelected] = useState<DocType | null>(null);
  const [form, setForm] = useState<Record<string, string>>({});
  const [generating, setGenerating] = useState(false);
  const [vaultSaving, setVaultSaving] = useState(false);

  const setField = (key: string) => (val: string) => setForm(f => ({ ...f, [key]: val }));

  const buildHTML = () => {
    if (selected === 'rate_confirmation') return buildRateConfirmationHTML(form);
    if (selected === 'proof_of_delivery') return buildPODHTML(form);
    return buildInvoiceHTML(form);
  };

  const generate = async () => {
    if (!selected) return;
    setGenerating(true);
    try {
      const { uri } = await Print.printToFileAsync({ html: buildHTML(), base64: false });
      const canShare = await Sharing.isAvailableAsync();
      if (canShare) {
        await Sharing.shareAsync(uri, { mimeType: 'application/pdf', dialogTitle: 'Share Document' });
      } else {
        await Print.printAsync({ uri });
      }
    } catch (err: any) {
      Alert.alert('Error', err.message ?? 'Failed to generate PDF');
    } finally {
      setGenerating(false);
    }
  };

  const saveToVault = async () => {
    if (!selected) return;
    setVaultSaving(true);
    try {
      const { uri } = await Print.printToFileAsync({ html: buildHTML(), base64: false });
      const docInfo = DOC_TYPES.find(d => d.type === selected)!;
      const fileName = `${docInfo.label}${form.loadNumber ? ` — ${form.loadNumber}` : ''}`;
      await uploadDocument(fileName, { uri, type: 'application/pdf', name: `${docInfo.label.replace(/ /g, '_')}.pdf` });
      Alert.alert('Saved!', `${docInfo.label} saved to your Document Vault.`);
    } catch (err: any) {
      Alert.alert('Error', err.message ?? 'Could not save to vault.');
    } finally {
      setVaultSaving(false);
    }
  };

  if (!selected) {
    return (
      <SafeAreaView style={s.container} edges={['top', 'bottom']}>
        <ScrollView contentContainerStyle={s.picker}>
          <Text style={s.heading}>Generate Document</Text>
          <Text style={s.subheading}>Select a document type to fill out and export as PDF</Text>
          {DOC_TYPES.map(dt => (
            <TouchableOpacity
              key={dt.type}
              style={[s.typeCard, { borderColor: dt.color }]}
              onPress={() => { setSelected(dt.type); setForm({}); }}
              activeOpacity={0.8}
            >
              <View style={[s.typeIcon, { backgroundColor: dt.color + '22' }]}>
                <Ionicons name={dt.icon as any} size={32} color={dt.color} />
              </View>
              <View style={{ flex: 1 }}>
                <Text style={s.typeLabel}>{dt.label}</Text>
                <Text style={s.typeDesc}>{dt.desc}</Text>
              </View>
              <Ionicons name="chevron-forward" size={20} color={Colors.textMuted} />
            </TouchableOpacity>
          ))}
        </ScrollView>
      </SafeAreaView>
    );
  }

  const docInfo = DOC_TYPES.find(d => d.type === selected)!;
  const fields = FIELDS[selected];


  return (
    <SafeAreaView style={s.container} edges={['top', 'bottom']}>
      <View style={s.formHeader}>
        <TouchableOpacity onPress={() => setSelected(null)} style={s.backBtn}>
          <Ionicons name="arrow-back" size={22} color={Colors.white} />
        </TouchableOpacity>
        <View style={{ flex: 1 }}>
          <Text style={s.formTitle}>{docInfo.label}</Text>
          <Text style={s.formSubtitle}>Fill in the details below</Text>
        </View>
      </View>

      <ScrollView contentContainerStyle={s.formBody} keyboardShouldPersistTaps="handled">
        {fields.map(({ label, key, ph, kbd }) => (
          <View key={key}>
            <Text style={s.fieldLabel}>{label}</Text>
            <TextInput
              style={s.fieldInput}
              value={form[key] ?? ''}
              onChangeText={setField(key)}
              placeholder={ph}
              placeholderTextColor={Colors.textMuted}
              keyboardType={kbd ?? 'default'}
              autoCapitalize="none"
            />
          </View>
        ))}

        <TouchableOpacity
          style={[s.generateBtn, generating && { opacity: 0.6 }, { backgroundColor: docInfo.color }]}
          onPress={generate}
          disabled={generating}
        >
          {generating ? (
            <ActivityIndicator size="small" color="#fff" />
          ) : (
            <>
              <Ionicons name="document-text-outline" size={20} color="#fff" />
              <Text style={s.generateText}>Generate PDF</Text>
            </>
          )}
        </TouchableOpacity>

        <TouchableOpacity
          style={[s.generateBtn, vaultSaving && { opacity: 0.6 }, { backgroundColor: '#2ECC71', marginTop: 10 }]}
          onPress={saveToVault}
          disabled={vaultSaving}
        >
          {vaultSaving ? (
            <ActivityIndicator size="small" color="#fff" />
          ) : (
            <>
              <Ionicons name="cloud-upload-outline" size={20} color="#fff" />
              <Text style={s.generateText}>Save to Vault</Text>
            </>
          )}
        </TouchableOpacity>
        <View style={{ height: 40 }} />
      </ScrollView>
    </SafeAreaView>
  );
}
